### ISSUE TITLE
No possible move in bidding stage

### ISSUE THREAD

**Issue by wtong2017** [abishekpuri/Seep_AI#1]
![image](https://user-images.githubusercontent.com/31873575/48671752-fcc92680-eb67-11e8-96b2-05e2757d4ecb.png)

No possible move in bidding stage but need to choose a move from a empty list because I can bid the value that is not exist in my hand.

**Comment by abishekpuri** [comment]
I will stop the bid value request being free typing, and will make it an option. That way user cannot input a bid value that doesn't exist.
